### ISSUE TITLE
NISC Software

### ISSUE THREAD

**Issue by cmisztur** [Jasonbluefire/POA_WoViewer#1]
Did you know there seems to be an alternative view of the data at this url: [https://ebill.butlerrural.coop/oms/outageMap](https://ebill.butlerrural.coop/oms/outageMap)?

**Comment by Jasonbluefire** [comment]
That is awsome, I did not know about it.

It looks like an older version of their software, and is not available for all of the companies who use woviewer, however the older map is really easy to import so that will cover a lot of these.

Thank-you

Examples of one's who don't have the older version implemented: 
https://ebill.teammidwest.com/woViewer/mapviewer.html?config=Outage+Web+Map
https://ebill.washingtonelectric.coop/woViewer/mapviewer.html?config=Outage+Web+Map
https://ebill.citizenselectric.com/woViewer/mapviewer.html?config=Outage+Web+Map

**Comment by cmisztur** [comment]
There has to be an API into this software.  Have you just tried reaching out to NISC or even one of the local utility companies?  Maybe you can get an IT guy that knows.

**Comment by Jasonbluefire** [comment]
The only API I have found is the one that feeds the site, which is set up in this repo. 

I have tried reaching out to NISC a few times with no response, I have not tried contacting the utilities themselves.

**Comment by cmisztur** [comment]
I would love to see your work running on a Splunk instance.

**Comment by Jasonbluefire** [comment]
I have imported every known woviewer application that still has the older version running.

Thanks again.
